# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: windows-latest

resources:
  repositories:
  - repository: MyGitHubRepo1 # The name used to reference this repository in the checkout step
    type: github
    endpoint: GitHub connection 1
    name: poyu-huang/CustomWebSite/CashApp
    trigger:
    - master
  - repository: MyGitHubRepo2 # The name used to reference this repository in the checkout step
    type: github
    endpoint: GitHub connection 1
    name: poyu-huang/CustomWebSite/BookmarkApp
    trigger:
    - master

# parameters:
#   - name: RestoreBuildProjects
#     type: string
#     values:
#     - '**/*.csproj'
#     - '!*Tests/*.csproj'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    # projects: '$(Parameters.RestoreBuildProjects)'
    projects: |
      **/*.csproj
      !*Tests/*.csproj

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: |
      **/*.csproj
      !*Tests/*.csproj
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: false
    projects: |
      **/*.csproj
      !*Tests/*.csproj
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()